-- ============================================================
-- Categorias de reunião — Gestão de Reuniões
--
-- Rode uma vez no painel do Supabase: SQL Editor › New query › cole este
-- arquivo inteiro › Run. Pode rodar de novo sem problema: nada é duplicado
-- e as regras são recriadas iguais.
--
-- É uma lista só, igual para todos os professores ("Feedback",
-- "Atualização de aulas"…). Quem está logado lê; só administrador
-- (professores.papel = 'admin', a mesma regra do Sistema de Presença) cria
-- categoria nova. A chave anônima não lê nem grava nada aqui.
-- ============================================================

create table if not exists public.categorias_reuniao (
  id bigint generated by default as identity primary key,
  nome text not null check (char_length(btrim(nome)) between 1 and 60),
  icone text not null default 'balao',   -- desenho do cartão (lista em frontend/features/categorias/icones.js)
  criado_por uuid default auth.uid() references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

comment on table public.categorias_reuniao is
  'Categorias de reunião da Gestão de Reuniões: uma lista só, igual para todos os professores.';

-- Sem nome repetido: "Feedback" e "feedback " são a mesma categoria.
create unique index if not exists categorias_reuniao_nome_unico
  on public.categorias_reuniao (lower(btrim(nome)));

-- Quem é admin, pela tabela professores. "security definer" para a regra
-- não depender do que o RLS de professores deixa cada um ver.
create or replace function public.gestao_reunioes_eh_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.professores
    where user_id = auth.uid()
      and papel = 'admin'
  );
$$;

revoke execute on function public.gestao_reunioes_eh_admin() from public, anon;
grant execute on function public.gestao_reunioes_eh_admin() to authenticated;

-- ---------- Quem pode o quê (RLS) ----------

alter table public.categorias_reuniao enable row level security;

revoke all on table public.categorias_reuniao from anon;
grant select, insert on table public.categorias_reuniao to authenticated;

drop policy if exists categorias_reuniao_ler on public.categorias_reuniao;
create policy categorias_reuniao_ler
  on public.categorias_reuniao
  for select
  to authenticated
  using (true);

-- Só admin cria, e sempre em nome de quem está logado.
drop policy if exists categorias_reuniao_criar on public.categorias_reuniao;
create policy categorias_reuniao_criar
  on public.categorias_reuniao
  for insert
  to authenticated
  with check (
    public.gestao_reunioes_eh_admin()
    and criado_por = auth.uid()
  );

-- ---------- As duas primeiras categorias ----------

insert into public.categorias_reuniao (nome, icone)
values
  ('Feedback', 'balao'),
  ('Atualização de aulas', 'livro')
on conflict do nothing;
