-- ============================================================
-- Reuniões marcadas — Gestão de Reuniões
--
-- Rode uma vez no painel do Supabase: SQL Editor › New query › cole este
-- arquivo inteiro › Run. Precisa da tabela categorias_reuniao já criada.
-- Pode rodar de novo sem problema: nada é duplicado e as regras são
-- recriadas iguais.
--
-- Cada linha é uma reunião de uma categoria ("Feedback"…) com um
-- professor. Só administrador (professores.papel = 'admin') marca; o
-- professor vê as reuniões dele. O aviso por e-mail sai pela função
-- avisar-reuniao (supabase/functions/avisar-reuniao), que preenche
-- aviso_enviado_em quando o e-mail é aceito pelo Gmail.
-- ============================================================

-- professor_id precisa ter o mesmo tipo de professores.id (tabela do
-- Sistema de Presença), então o tipo é lido do próprio banco.
do $$
declare
  tipo_id text;
begin
  select format_type(atttypid, atttypmod) into tipo_id
  from pg_attribute
  where attrelid = 'public.professores'::regclass
    and attname = 'id';

  execute format($tabela$
    create table if not exists public.reunioes (
      id bigint generated by default as identity primary key,
      professor_id %s not null references public.professores (id) on delete cascade,
      categoria_id bigint not null references public.categorias_reuniao (id),
      inicio timestamptz not null,
      duracao_min integer not null check (duracao_min between 5 and 480),
      formato text not null check (formato in ('presencial', 'online')),
      local text check (char_length(local) <= 500),     -- sala ou link da chamada
      pauta text check (char_length(pauta) <= 2000),
      aviso_enviado_em timestamptz,                      -- null = o e-mail ainda não saiu
      criado_por uuid default auth.uid() references auth.users (id) on delete set null,
      created_at timestamptz not null default now()
    )
  $tabela$, tipo_id);
end
$$;

comment on table public.reunioes is
  'Reuniões da Gestão de Reuniões: uma categoria (Feedback…) com um professor, num dia e horário.';

-- A página do professor busca as próximas reuniões dele.
create index if not exists reunioes_professor_inicio
  on public.reunioes (professor_id, inicio);

-- Quem é admin, pela tabela professores (a mesma função criada junto com
-- as categorias; recriada aqui igual para este arquivo valer sozinho).
create or replace function public.gestao_reunioes_eh_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.professores
    where user_id = auth.uid()
      and papel = 'admin'
  );
$$;

revoke execute on function public.gestao_reunioes_eh_admin() from public, anon;
grant execute on function public.gestao_reunioes_eh_admin() to authenticated;

-- ---------- Quem pode o quê (RLS) ----------

alter table public.reunioes enable row level security;

-- Logado lê e marca (as políticas abaixo filtram quem); da reunião já
-- marcada, só a marca de aviso enviado pode mudar. A chave anônima não
-- acessa nada.
revoke all on table public.reunioes from anon, authenticated;
grant select, insert on table public.reunioes to authenticated;
grant update (aviso_enviado_em) on table public.reunioes to authenticated;

-- Admin vê todas; o professor, só as dele.
drop policy if exists reunioes_ler on public.reunioes;
create policy reunioes_ler
  on public.reunioes
  for select
  to authenticated
  using (
    (select public.gestao_reunioes_eh_admin())
    or exists (
      select 1
      from public.professores p
      where p.id = reunioes.professor_id
        and p.user_id = (select auth.uid())
    )
  );

-- Só admin marca, e sempre em nome de quem está logado.
drop policy if exists reunioes_marcar on public.reunioes;
create policy reunioes_marcar
  on public.reunioes
  for insert
  to authenticated
  with check (
    (select public.gestao_reunioes_eh_admin())
    and criado_por = (select auth.uid())
  );

-- A função avisar-reuniao roda como o admin que a chamou e registra aqui
-- que o e-mail saiu.
drop policy if exists reunioes_registrar_aviso on public.reunioes;
create policy reunioes_registrar_aviso
  on public.reunioes
  for update 
  to authenticated
  using ((select public.gestao_reunioes_eh_admin()))
  with check ((select public.gestao_reunioes_eh_admin()));
